[package]
name = "near-lake-framework"
version = "0.0.0"                                                          # managed by cargo-workspaces, see below
license = "MIT OR Apache-2.0"
repository = "https://github.com/near/near-lake-framework"
description = "Library to connect to the NEAR Lake S3 and stream the data"
categories = ["asynchronous", "api-bindings", "network-programming"]
keywords = ["near", "near-lake", "near-indexer"]
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
rust-version = "1.58.1"

# cargo-workspaces
[workspace.metadata.workspaces]
version = "0.4.0"

[dependencies]
anyhow = "1.0.51"
aws-config = "0.11.0"
aws-endpoint = "0.11.0"
aws-types = "0.11.0"
aws-sdk-s3 = "0.11.0"
aws-smithy-http = "0.41.0"
derive_builder = "0.11.2"
futures = "0.3.5"
itertools = "^0.10.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.75"
tokio = { version = "1.1", features = ["sync", "time"] }
tokio-stream = { version = "0.1" }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer-primitives = "0.12.0"
